sonar-projectKey=ob-openbar-auth
sonar.projectName=OPENBAR Auth
sonar.projectVersion=1.0.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.java.source=21
sonar.java.target=21

sonar.kotlin.source=src/main/kotlin
sonar.kotlin.test=src/test/kotlin

sonar.tests=src/test
sonar.junit.reportPaths=**/build/test-results/test/

sonar.coverage.jacoco.xmlReportPaths=**/build/reports/jacoco/test/jacocoTestReport.xml

sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=kotlin:S1172
sonar.issue.ignore.multicriteria.e1.language=kt
sonar.issue.ignore.multicriteria.e2.ruleKey=kotlin:S138
sonar.issue.ignore.multicriteria.e2.language=kt

sonar.exclusions=**/build/**,**/node_modules/**,**/.gradle/**
sonar.coverage.exclusions=**/test/**,**/*Test.kt,**/*Tests.kt,**/config/**
